# Default initial positions for allegro_hand's ros2_control fake system

initial_positions:
  joint_0_0: 0
  joint_1_0: 0
  joint_2_0: 0
  joint_3_0: 0
  joint_4_0: 0
  joint_5_0: 0
  joint_6_0: 0
  joint_7_0: 0
  joint_8_0: 0